SmsApi/SmsApi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sms_handler/', include('sms_handler.urls'))
]

SmsApi/sms_handler/urls.py
from django.urls import path
from .views import SmsSenderApiView, NewSmsFormApiView


app_name = 'sms_handler'

urlpatterns = [
    path('send/', SmsSenderApiView.as_view(), name='send'),
    path('new/', NewSmsFormApiView.as_view(), name='new_form')
]

SmsApi/sms_handler/models.py
from django.db import models
from django.core.validators import RegexValidator


class Sms(models.Model):
    phone_regex = RegexValidator(regex=r'^\d{11}$',
                                 message="Phone number must be entered in the format: '09011001010'. 11 digits allowed.")
    phone_number_receptor = models.CharField(validators=[phone_regex], max_length=12, verbose_name='receptor')
    message = models.CharField(max_length=150, verbose_name="Message content")

SmsApi/sms_handler/views.py
from django.http import HttpResponseRedirect
from rest_framework.response import Response
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny
from .serializers import SmsSerializer
from .models import Sms
from django.shortcuts import reverse
from rest_framework.views import APIView
from rest_framework.renderers import TemplateHTMLRenderer


class NewSmsFormApiView(APIView):
    template_name = 'sms_handler/index.html'
    renderer_classes = [TemplateHTMLRenderer]
    permission_classes = [AllowAny]

    def get(self, request):
        return Response({})


class SmsSenderApiView(CreateAPIView):
    serializer_class = SmsSerializer
    queryset = Sms.objects.all()
    permission_classes = [AllowAny]

    def create(self, request, *args, **kwargs):
        super().create(request, *args, **kwargs)
        return HttpResponseRedirect(redirect_to=reverse('sms_handler:new_form'))

SmsApi/sms_handler/templates/sms_handler/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            crossorigin="anonymous">
        <title>Send SMS</title>
    </head>

    <body>
        <div class="container" dir="ltr">
            <h1>Send new Message</h1>


            <form action="{% url 'sms_handler:send' %}" method="post" class="form">
            {% csrf_token %}
                <label for="message">Message Content:</label>
                <br>
                <input type="text" name="message" id="message" maxlength="150" required>
                <br>
                <label for="phone_number_receptor">Phone number:</label>
                <br>
                <input type="tel" name="phone_number_receptor" id="phone_number_receptor" placeholder="09361457810" pattern="[0-9]{11}" required>
                <br>
                <input type="submit" value="Send">
            </form>
        </div>
    </body>
</html>